### DISCUSSION TITLE
我想要进一步减少kindling-collector运行时所占用的cpu跟内存

### DISCUSSION THREAD

**Discussion by zcl1115** [harmonycloud/kindling#601] [agent collector] [answered]
如题，我想要进一步压缩kindling-collector运行时占用的cpu跟内存大小，目前我们关闭了cpuanalyzer、noopanalyzer、k8sinfoanalyzer、tcpconnectanalyzer跟tcpmetricanalyzer，仅保留network这一分析器，同时监听的事件被压缩到以下几种，想问一下如果只是想要request_io、response_io、request_total_time这三种指标，还能不能进一步移除什么事件的订阅
- name: syscall_exit-writev
  category: net
- name: syscall_exit-readv
  category: net
- name: syscall_exit-write
  category: net
- name: syscall_exit-read
  category: net
- name: syscall_exit-sendto
  category: net
- name: syscall_exit-recvfrom
  category: net
- name: syscall_exit-sendmsg
  category: net
- name: syscall_exit-recvmsg
  category: net
- name: syscall_exit-sendmmsg
  category: net

还想问一下的是，我这边开启了tcpmetricanalyzer，但是没有在9500暴露的metrics中找到丢包、重传等指标，是需要修改什么吗

**Comment by dxsup** [comment]
> 想问一下如果只是想要request_io、response_io、request_total_time这三种指标，还能不能进一步移除什么事件的订阅

不能了，这些都是生成这三种指标的基础事件。

> 还想问一下的是，我这边开启了tcpmetricanalyzer，但是没有在9500暴露的metrics中找到丢包、重传等指标，是需要修改什么吗

要获得丢包、重传等指标，需要订阅以下几类事件：
```yaml
      - name: kprobe-tcp_close
      - name: kprobe-tcp_rcv_established
      - name: kprobe-tcp_drop
      - name: kprobe-tcp_retransmit_skb
```
